name: mergemod
channels:
    - conda-forge
dependencies:
    - astropy
    - cartopy
    - conda-build
    - ducc0
    - fftw
    - flake8
    - gmt
    - jupyter
    - liblapack
    - matplotlib-base
    - numpy
    - palettable
    - pandas
    - pooch
    - pygmt
    - pyshtools
    - python
    - requests
    - scipy
    - xarray
    - pip
    - cmcrameri
    