name: mergemod
channels:
    - conda-forge
dependencies:
    - python
    - fftw
    - liblapack
    - numpy
    - scipy
    - matplotlib-base
    - xarray
    - pooch
    - pandas
    - cartopy
    - pyshtools
    - jupyter
    - ducc0
    - pytest
    - pyyaml
    